### ISSUE TITLE
Orange text in Journals

### ISSUE THREAD

**Issue by Ansigtet** [kbender84/coriolis-kbender-ui#1]
If you own any of the official free league VTT stuff, the orange text is hard to read, on their blue/white background in the journals. Maybe a darker hue could work.
![image (1)](https://user-images.githubusercontent.com/129210900/228321968-32843f55-b7b4-4b5d-ac24-cd5e566875c5.png)

**Comment by kbender84** [comment]
Fixed in 1.2.4
