### ISSUE TITLE
Update module to support Foundry V11

### ISSUE THREAD

**Issue by r-valyar** [kbender84/coriolis-kbender-ui#2]
Would it be possible to review and update the module to support Foundry v11? All Coriolis products (commercial) have been updated and I believe it is good moment to get v11 supported :)

**Comment by kbender84** [comment]
Oh joy! Upgrade to v11 :) Put on your seatbelts :)
Will try.

**Comment by kbender84** [comment]
Ok, should work now, feel free to test (worked for me and I didn't notice anything bad happening)

**Comment by r-valyar** [comment]
I think it looks good, nothing immediate. Just one thing - the module updates itself to the same version

![image](https://github.com/kbender84/coriolis-kbender-ui/assets/63558984/9288a508-fbb4-4517-9538-c2561dcff897)

**Comment by kbender84** [comment]
yeah, I just removed the line that was blocking it with Foundry 11, so didn't push the version update ;)

**Comment by r-valyar** [comment]
I have to uninstall/re-install the module or there will be new release?

**Comment by kbender84** [comment]
everything should work by default.


In the module description I initially put line "maximum foundry version: 10". I have removed it, checked the module and reuploaed the module.json file with the same foundry number. Nothing was changed in the code, so the update above should work fine. If you have noticed any specific bug, I can work on it, and try to fix it (and if there would be code update necessary, I will increase the version to 1.3).

**Comment by r-valyar** [comment]
When I initiate update from Foundry, the module updates every time to itself. 
![image](https://github.com/kbender84/coriolis-kbender-ui/assets/63558984/ffe425f7-a733-4a03-89d5-e9f3a8ee7dcb)

The actual manifest we are getting from you is:
![image](https://github.com/kbender84/coriolis-kbender-ui/assets/63558984/ce32378f-5368-4001-bb76-b0b38309ce4c)

**Comment by kbender84** [comment]
ok, you have convinced me, I have to solve the numbering mess.

**Comment by kbender84** [comment]
ok, all updated to version 1.3.0, should work fine now in updater and share proper filepaths (no lazy paths this time)

**Comment by r-valyar** [comment]
I think it looks good now. After the update and removal/re-install of the module, I get 1.3.0 properly. Thanks
